### ISSUE TITLE
MemoryError on Windows 7 using Python 3.4 (Anaconda dist)

### ISSUE THREAD

**Issue by jboynyc** [getlogbook/logbook#137] opened 2015-03-23 19:17 UTC
I'm running Python 3.4 (Anaconda distribution) on Windows 7. I installed Nikola (which uses `logbook`) using `pip`. Trying to run `nikola`, `logbook` throws the following error:

    Traceback (most recent call last):
      File "C:\Users\jboy1\Applications\Anaconda\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "C:\Users\jboy1\Applications\Anaconda\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\jboy1\Applications\Anaconda\Scripts\nikola.exe\__main__.py", line 5, in <module>
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\__init__.py", line 33, in <module>
        from .nikola import Nikola  # NOQA
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\nikola.py", line 56, in <module>
        from .post import Post
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\post.py", line 40, in <module>
        from . import utils
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\nikola\utils.py", line 46, in <module>
        import logbook
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\logbook\__init__.py", line 14, in <module>
        from logbook.base import LogRecord, Logger, LoggerGroup, NestedSetup, \
      File "C:\Users\jboy1\Applications\Anaconda\lib\site-packages\logbook\base.py", line 23, in <module>
        from logbook._speedups import group_reflected_property, \
    MemoryError

I tried the same in a Python 2.7 environment of the same Anaconda distribution, and that works fine.

**Comment by brainstorm** [comment] 2015-10-06 10:20
Hello @aldanor (from issue #119), @jboynyc,

Unfortunately we have no way to test this properly on windows machines since we do not own any at the moment. Hopefully TravisCI will support windows in the future:

https://github.com/travis-ci/travis-ci/issues/216

Until then, I'm afraid that we cannot give full support for that platform and we'll have to rely on you guys spotting those bugs (and hopefully fixing them).

**Comment by aldanor** [comment] 2015-10-06 10:27
@brainstorm There's AppVeyor which everyone on GitHub now seems to use to run Windows tests. It takes little time to setup, sort of the same thing as Travis.

Here's one random example for reference:
- https://github.com/jkbrzt/httpie/blob/master/appveyor.yml

**Comment by brainstorm** [comment] 2015-10-06 10:35
@aldanor, @jboynyc, Care to try it on your branch and PR when tests are green for windows? That would be great to have for some stall windows-only issues we have in the bug tracker which we cannot test out :/

**Comment by aldanor** [comment] 2015-10-06 10:39
@brainstorm That would be pretty hard to do for me since I don't currently have a Windows box either and I barely use Windows at all other than at work once in a while....

Setting up appveyor is easy enough, but fixing all windows bugs would take a bit of effort...

**Comment by RazerM** [comment] 2015-11-28 19:47
@jboynyc Does this still happen? I can't reproduce on Anaconda, Python 3.4, x64

**Comment by brainstorm** [comment] 2015-12-02 15:01
I got this spurious issue with a totally unrelated package (`cyvcf2`) a few days ago, went away after reinstalling... Besides, the Appveyor continuous integration seems to roll fine and has been re-deployed a bunch of times now on Windows platforms. @jboynyc, let us know if still is an issue for you. Closing.

**Closed by brainstorm** 2015-12-02 15:01 UTC

**Comment by jboynyc** [comment] 2015-12-08 15:54
It hasn't recurred, but I haven't reproduced the same circumstances in a while. Close is fine with me.

**Comment by jmtaysom** [comment] 2016-10-26 16:21
I am getting a memory error when I try using coverage. I am also on windows 7.
